### ISSUE TITLE
Nginx 1.13

### ISSUE THREAD

**Issue by Ulrar** [darylounet/libnginx-mod-pagespeed#1]
Hey,

I've been using this repo and it's been working fine, but it looks like nginx 1.13 has been released and now pagespeed won't install since the nginx version isn't 1.12. Any plan on supporting 1.13 soon ?

**Comment by darylounet** [comment]
Hi,
I was thinking that NGiNX 1.13 branch was a beta version, but [this serverfault answer](https://serverfault.com/questions/715049/what-s-the-difference-between-the-mainline-and-stable-branches-of-nginx) changed my thought.
Now I just have to find the time to do this ;-)

**Comment by alasdaircr** [comment]
@darylounet hi - any update on this?

**Comment by darylounet** [comment]
It's done on [mainline git branch](https://github.com/darylounet/libnginx-mod-pagespeed/tree/mainline) and available on [packagecloud](https://packagecloud.io/DaryL/libnginx-mod-pagespeed).
Can you please test it and tell me if it works ?

**Comment by darylounet** [comment]
I've deleted 1.13 packages on packagecloud, there is a package conflict. I have to make another packagecloud repository for mainline branch.

**Comment by Ulrar** [comment]
Hey,

Just took a look, and now it seems the packages are for ningx 1.14, which as far as I can tell aren't in the official nginx repository yet, at least for stretch. Could you fix that, probably just by downgrading back to 1.13 ?
Or maybe have a different repo per version, but currently I just don't see a way to use the repo :(

**Comment by darylounet** [comment]
This is because you are using mainline repository, on stable repo you can have nginx 1.14 : 
https://nginx.org/packages/debian/pool/nginx/n/nginx/nginx_1.14.0-1~stretch_amd64.deb

By the way, [NGiNX 1.15 is available](https://nginx.org/en/CHANGES) on mainline repo, so I keep this thread open !

**Comment by darylounet** [comment]
I have released the mainline version under another repository :
https://packagecloud.io/DaryL/libnginx-mod-pagespeed-mainline

It seems to work, see #3 .

Can you test it too @Ulrar please ?
/cc @alasdaircr

**Comment by darylounet** [comment]
1.17 Mainline is now available.
