### ISSUE TITLE
Update for nginx 1.24

### ISSUE THREAD

**Issue by xPaw** [darylounet/libnginx-mod-pagespeed#12]
That's the current stable version.

**Comment by darylounet** [comment]
Hi,
the PageSpeed project is not maintained anymore, projects are archived :
https://github.com/apache/incubator-pagespeed-ngx/
https://github.com/apache/incubator-pagespeed-mod

There are topics about hacks to get project compiled : https://github.com/apache/incubator-pagespeed-ngx/issues/1760
But I have no free time to do that.
Feel free to contribute.
