### ISSUE TITLE
nginx version 1.14.0-0~xenial

### ISSUE THREAD

**Issue by klarre1** [darylounet/libnginx-mod-pagespeed#2]
Im trying to install libnginx-mod-pagespeed_1.13.35.2+nginx-1.14.0-1~xenial_amd64.deb on Ubuntu 16.04
But when upgrading nginx on Ubuntu using stable build I only get nginx version 1.14.0-0~xenial the module only seems to work with 1.14.0-1~xenial do you know if there is something I can do to get the 1.14.0-1~xenial version or to get your module to work on 1.14.0-0~xenial

**Comment by darylounet** [comment]
Hi @klarre1 you have to install NGiNX from official repository : https://nginx.org/en/linux_packages.html#stable

For Ubuntu Xenial execute this :
```bash
echo "deb http://nginx.org/packages/ubuntu/ xenial nginx" >> /etc/apt/sources.list.d/nginx.list
apt-get update
apt-cache policy nginx
```
