### ISSUE TITLE
1.15.5-1~stretch

### ISSUE THREAD

**Issue by breyer** [darylounet/libnginx-mod-pagespeed#3]
Will you update to the latest release?

**Comment by darylounet** [comment]
Yes it's in my todo list, surely in the next two weeks (but it will be in a different repo to avoid conflicts with stable branch).

**Comment by darylounet** [comment]
Hi @breyer can you try with the new mainline repository please ?
https://packagecloud.io/DaryL/libnginx-mod-pagespeed-mainline

**Comment by breyer** [comment]
Works immediately. Thanks a lot @darylounet !
