### ISSUE TITLE
Debian 10 support

### ISSUE THREAD

**Issue by krzaczek** [darylounet/libnginx-mod-pagespeed#6]
Any ETA for a debian 10 package ?

**Comment by darylounet** [comment]
Debian Buster is now supported in both stable and mainline, thanks for the information.

**Comment by adrelanos** [comment]
Could you please upload to https://packagecloud.io/DaryL/libnginx-mod-pagespeed ?

**Comment by darylounet** [comment]
> Could you please upload to https://packagecloud.io/DaryL/libnginx-mod-pagespeed ?

It is already : https://packagecloud.io/DaryL/libnginx-mod-pagespeed/packages/debian/buster/libnginx-mod-pagespeed_1.13.35.2+nginx-1.16.1-1~buster_amd64.deb
