### ISSUE TITLE
v1.14.36.1 is out

### ISSUE THREAD

**Issue by paskal** [darylounet/libnginx-mod-pagespeed#9]
Hi there, thank you for your effort! New version [is out](https://www.modpagespeed.com/doc/release_notes#release_1.14.36.1), I wonder if it's possible to get a new build for it?

**Comment by darylounet** [comment]
Hello ! Thank you for your support ! Unfortunately the new version you mention is about the Apache module, The latest NGiNX stable module version is 1.13.35.2 and there is also a release candidate v1.14.33.1-RC1 :
https://github.com/apache/incubator-pagespeed-ngx/releases
